[package]
authors = ["The Rust Project Developers"]
name = "rbml"
version = "0.0.0"

[lib]
name = "rbml"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
log = { path = "../liblog" }
serialize = { path = "../libserialize" }

[dev-dependencies]
test = { path = "../libtest" }
