[package]
authors = ["The Rust Project Developers"]
name = "rustc_lint"
version = "0.0.0"

[lib]
name = "rustc_lint"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
log = { path = "../liblog" }
rustc = { path = "../librustc" }
syntax = { path = "../libsyntax" }
