[package]
authors = ["The Rust Project Developers"]
name = "rustc_typeck"
version = "0.0.0"

[lib]
name = "rustc_typeck"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
log = { path = "../liblog" }
syntax = { path = "../libsyntax" }
arena = { path = "../libarena" }
fmt_macros = { path = "../libfmt_macros" }
rustc = { path = "../librustc" }
rustc_platform_intrinsics = { path = "../librustc_platform_intrinsics" }
