[package]
authors = ["The Rust Project Developers"]
name = "rustdoc"
version = "0.0.0"
build = "build.rs"

[lib]
name = "rustdoc"
path = "lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
arena = { path = "../libarena" }
getopts = { path = "../libgetopts" }
rustc = { path = "../librustc" }
rustc_driver = { path = "../librustc_driver" }
rustc_trans = { path = "../librustc_trans" }
rustc_resolve = { path = "../librustc_resolve" }
rustc_lint = { path = "../librustc_lint" }
rustc_back = { path = "../librustc_back" }
serialize = { path = "../libserialize" }
syntax = { path = "../libsyntax" }
test = { path = "../libtest" }
log = { path = "../liblog" }

[build-dependencies]
build_helper = { path = "../build_helper" }
gcc = "0.3"
