[package]
authors = ["The Rust Project Developers"]
name = "libc"
version = "0.0.0"

[lib]
name = "libc"
path = "lib.rs"

[dependencies]
core = { path = "../libcore" }

[dev-dependencies]
std = { path = "../libstd" }
test = { path = "../libtest" }
