[package]
authors = ["The Rust Project Developers"]
name = "compiletest"
version = "0.0.0"
build = "build.rs"

[[bin]]
name = "compiletest"
path = "compiletest.rs"

[build-dependencies]
build_helper = { path = "../build_helper" }